### ISSUE TITLE
Inconsistent damage between weapon variations

### ISSUE THREAD

**Issue by kingultron99** [StarCitizenWiki/API#100]
I'm finding it a little strange that a weapon with a slightly different paint can change its damage properties, here are some examples i've encountered so far

FS-9 LMG returns: `damages: [ { type: 'impact', name: 'physical', damage: 3 } ]`
FS-9 "Evergreen" LMG returns: `damages: [ { type: 'impact', name: 'distortion', damage: 35 } ]`
FS-9 "Finish Line" LMG returns: `damages: [ { type: 'impact', name: 'physical', damage: 15 } ]`

A03 Sniper Rifle returns: `damages: [ { type: 'impact', name: 'physical', damage: 10.5 } ]`
A03 "Canuto" Sniper Rifle returns: `damages: [ { type: 'impact', name: 'stun', damage: 1 } ]`

Arclight Pistol returns: `damages: [ { type: 'impact', name: 'energy', damage: 15 } ]`
Arclight "Herrero" Pistol returns: `damages: [ { type: 'impact', name: 'stun', damage: 10 } ]`

**Comment by octfx** [comment]
Strange indeed, gonna look into it!
