### ISSUE TITLE
Adding data for location turrets

### ISSUE THREAD

**Issue by alistair3149** [StarCitizenWiki/API#103]
There are various ground turrets implemented in game. It will be useful to have the stats of the turrets since they are increasing common in missions related to outpost

* `BEHR_groundturret_AA_S4`
* `BRAA_groundturret_AA`
* `BRAA_groundturret_AP_S1`

**Comment by octfx** [comment]
I could only find the `AAT-34 Turret` in some of its variations. (BRAA_groundturret_AA), the _S4 and _S1 names didn't match anything.

https://api.star-citizen.wiki/api/v2/items/a34be69f-2a83-4c98-bc01-9e9190128d17
https://api.star-citizen.wiki/api/v2/items/b3ad64dd-8ad9-4a6e-953b-08f87e32a253
https://api.star-citizen.wiki/api/v2/items/b4b5e78b-aac5-462f-aa7e-e98e95197833
https://api.star-citizen.wiki/api/v2/items/bf1899b2-2ba6-4602-9d1e-3e83b133f689
https://api.star-citizen.wiki/api/v2/items/07fda541-7c95-461f-a940-ea92a7f3c8ba

**Comment by alistair3149** [comment]
Actually please ignore my post. The data are available and I wasn't looking at the right places :P
