### ISSUE TITLE
Some BEHR optics attachments is returning null in iron_sight

### ISSUE THREAD

**Issue by alistair3149** [StarCitizenWiki/API#105]
Both `magnification` and `optic_type`  under `iron_sight` are returning `null` for the following items:
https://api.star-citizen.wiki/api/v2/items/a392c30b-5798-4b35-a70c-01264c6a083e
https://api.star-citizen.wiki/api/v2/items/0dabf62d-9b3e-4968-a371-ae0cb44057a1

As opposed to the 16x sight which has the data:
https://api.star-citizen.wiki/api/v2/items/77521326-082c-44f9-a5b2-09dfb87f3f14

**Comment by octfx** [comment]
The iron sight data is currently taken from the item description, as the xml data had invalid data in the past.

Both linked iron sights have an empty description in-game, resulting in missing data
![image](https://github.com/StarCitizenWiki/API/assets/6594492/9d77b671-0a9d-47bc-9354-8388bdd37fe1)

**Comment by octfx** [comment]
Imported some more data in [1180f00](https://github.com/StarCitizenWiki/API/commit/1180f00f57f42ff439fe244fe8e6d7f970cf6b7f)
