### ISSUE TITLE
ADP-mk4 Core Red Alert not listed as a variant of ADP-mk4 Core Woodland

### ISSUE THREAD

**Issue by alistair3149** [StarCitizenWiki/API#112]
In the `variants` object of the [ADP-mk4 Core Woodland](https://api.star-citizen.wiki/api/v2/items/8eabeef4-5d8d-4db4-a4df-9fa151062b42?include=variants), [ADP-mk4 Core Red Alert](https://api.star-citizen.wiki/api/v2/items/2dd42197-7d07-490d-be2a-36b10247c2bc?include=variants) should be listed as a variant.

**Comment by octfx** [comment]
This is not yet live

**Comment by octfx** [comment]
Live
