### ISSUE TITLE
Include supported item type in item ports

### ISSUE THREAD

**Issue by alistair3149** [StarCitizenWiki/API#113]
The supported item type can be found under the `Types` key in the item port.
https://github.com/StarCitizenWiki/scunpacked-data/blob/53ee8b80e00548f283cbbe2b2b858a70b2c61d25/v2/items/rsi_odyssey_undersuit_01_01_01-raw.json#L188

**Comment by octfx** [comment]
![image](https://github.com/StarCitizenWiki/API/assets/6594492/abc7a1ed-5868-4180-99c5-1d90117d13da)
