### ISSUE TITLE
Various incorrect values for base_variant

### ISSUE THREAD

**Issue by alistair3149** [StarCitizenWiki/API#114]
* Cryptokeys such as [Walesko](https://api.star-citizen.wiki/api/v2/items/8c632754-3e85-42bd-b393-b072c6410808) have [FUNT](https://api.star-citizen.wiki/api/v2/items/dd788dd5-a2da-494d-a7de-b60a768f06e2) as base variant
* Mining modules such as the [Forel Module](https://api.star-citizen.wiki/api/v2/items/6c072263-8f32-4ca1-b64b-37d820b0786f) have [Mining Modules](https://api.star-citizen.wiki/api/v2/items/c771d921-e4b1-4e45-85fa-8b517aca3d70) as base variant
* [Animus Missile Launcher](https://api.star-citizen.wiki/api/v2/items/3666c8ac-d552-4006-8c47-7e8f773b11a4) have [Scourge Railgun](https://api.star-citizen.wiki/api/v2/items/699db405-4ca1-4993-ba58-a9f90001ae6b) as base variant

**Comment by octfx** [comment]
From the referenced commit:


> An item is assumed to have variants if its classname contains 01, 02, 03, etc.
>
> If this identifier is found, we assume that the very first id denotes a specific class, and all following ids denote variants.
> 
> Example: Scourge Railgun  
> Class Name: apar_special_ballistic_01 -> 01 marks class  
> Matched variant: `apar_special_ballistic_01_02`
> 
> Animus Missile Launcher  
> Class Name: apar_special_ballistic_02 -> 02 marks class  
> Matched variant: `apar_special_ballistic_02_03_01`

This now skips computing base ids for items without an `01, 02, etc.` in its class name.  
All mentioned items are fixed by this

**Comment by octfx** [comment]
All three fixed and deployed; Upstream cache will take a few hours
