### ISSUE TITLE
Error 500: Attempt to read property "damages" on null for multiple knives

### ISSUE THREAD

**Issue by alistair3149** [StarCitizenWiki/API#116]
https://api.star-citizen.wiki/api/v2/items/Demon%20Fang%20Combat%20Knife
https://api.star-citizen.wiki/api/v2/items/FSK-8%20Combat%20Knife
https://api.star-citizen.wiki/api/v2/items/Myondo%20Knife
https://api.star-citizen.wiki/api/v2/items/Njakte%20Knife
https://api.star-citizen.wiki/api/v2/items/Prison%20Shiv
https://api.star-citizen.wiki/api/v2/items/Sawtooth%20Combat%20Knife
https://api.star-citizen.wiki/api/v2/items/Sizi%20Knife

**Comment by octfx** [comment]
Validates all 12606 items locally, they all return 200 now
