### ISSUE TITLE
Import MeleeCombatConfig of melee weapon

### ISSUE THREAD

**Issue by alistair3149** [StarCitizenWiki/API#121]
Melee damage are currently missing from the API, it can be found in game data under `MeleeCombatConfig`.
For example, `da909c53-195a-4289-8466-ecb4c418f930` is the `MeleeCombatConfig` used by the FSK-8 Combat Knife.

**Comment by octfx** [comment]
![image](https://github.com/StarCitizenWiki/API/assets/6594492/1ac86b30-0d28-40bb-b260-7dd7a72e0b12)
