### ISSUE TITLE
Add faction data to API

### ISSUE THREAD

**Issue by alistair3149** [StarCitizenWiki/API#123]
Faction data seems to affect how NPCs interact with other NPCs in game.

`defaultReaction` and `factionRelationships` are helpful information to include. Here's the raw output from SCUnpacked for XenoThreat: https://github.com/StarCitizenWiki/scunpacked-data/blob/5eb71eb4b19e8462f610bae892747acbbb31caa9/factions/xenothreat.json

There are also mission giver data and reputation data separately, but they are not connected to faction data at all.

**Comment by alistair3149** [comment]
Seems that some of the factions are missing from the API.
For example, `03fa1a65-90e6-42f4-b23a-a6d3efd1157b` (XenoThreat) is not in the data set.

**Comment by octfx** [comment]
They are included, their name is just "Private Security"
![image](https://github.com/StarCitizenWiki/API/assets/6594492/00fe5d17-fbe9-4ba2-8ddf-05de18238d58)

**Comment by alistair3149** [comment]
Weird the UUID doesn't seem to work on the endpoint: https://api.star-citizen.wiki/api/v2/factions/03fa1a65-90e6-42f4-b23a-a6d3efd1157b

**Comment by octfx** [comment]
Fix wasn't live yet, url is working now
