### ISSUE TITLE
Missing tags for commodities

### ISSUE THREAD

**Issue by alistair3149** [StarCitizenWiki/API#124]
On the API, certain commodities such as the `Pingala seeds` (`ea165f19-e4a6-4ee4-86d3-a0364a6307bd`) does not have any value in the tags key, while it is not the case in the [raw data](https://github.com/StarCitizenWiki/scunpacked-data/blob/5eb71eb4b19e8462f610bae892747acbbb31caa9/v2/items/harvestable_pingala-raw.json#L3).

**Comment by octfx** [comment]
The tags key refers to these tags: https://github.com/StarCitizenWiki/scunpacked-data/blob/5eb71eb4b19e8462f610bae892747acbbb31caa9/v2/items/harvestable_pingala-raw.json#L52

The tags of an entity can now be found under the `entity_tags` key
