### ISSUE TITLE
UUID entry point

### ISSUE THREAD

**Issue by alistair3149** [StarCitizenWiki/API#50]
Feature request:
Would it be possible to route UUID to the correct API with only UUID?
For example, https://api.star-citizen.wiki/api/search/968249b2-ca7c-4b41-8f58-730673fefc8c would result in the Mustang Gamma Vehicle V2 API output (https://api.star-citizen.wiki/api/v2/vehicles/968249b2-ca7c-4b41-8f58-730673fefc8c).

**Comment by octfx** [comment]
I've changed the behavior of the `v2/items` endpoint.

If an item is a vehicle, the output should now be equal to `v2/vehicles` (sans shipmatrix data)

**Comment by alistair3149** [comment]
Closing as it is resolved
