### ISSUE TITLE
Add armor stats to vehicles

### ISSUE THREAD

**Issue by alistair3149** [StarCitizenWiki/API#52]
Would it be possible to add armor stats to the v2 vehicles API?

**Comment by octfx** [comment]
Certainly!
Using https://github.com/StarCitizenWiki/scunpacked-data/blob/master/items/armr_anvl_carrack.jsonas an example, which data points do you need?

**Comment by alistair3149** [comment]
Mainly damage multiplier. It should be good until armor mechanics is actually implemented to the game (likely not for a while though)
