### ISSUE TITLE
Incorrect name and slug for vehicles that only exist in game data

### ISSUE THREAD

**Issue by alistair3149** [StarCitizenWiki/API#54]
For example, [Stinger](https://api.star-citizen.wiki/api/v2/vehicles/Stinger) and [Void](https://api.star-citizen.wiki/api/v2/vehicles/Void) defaults to `Aurora ES` as their name.

**Comment by octfx** [comment]
Those ships were erroneously imported.
I’ll fix the output but am leaning towards removing those ships

**Comment by alistair3149** [comment]
Those ships do have working hardpoints and stats to be fair. I don't personally use the name parameter but it is still helpful to keep those in the API.

**Comment by octfx** [comment]
The ships in question were imported with version 3.13.1-LIVE.7445322 and have since seen no update. As they are ~2 years old I'll remove them for now

**Comment by alistair3149** [comment]
Closing since the problematic ships are removed
