### ISSUE TITLE
Speed data for ground vehicle

### ISSUE THREAD

**Issue by alistair3149** [StarCitizenWiki/API#56]
Would it be possible to add speed-related stats for ground vehicles in game? Here's a list that might be helpful:
- Max speed
- 0 to max speed time
- Turn rate

**Comment by octfx** [comment]
Data imported in https://github.com/StarCitizenWiki/scunpacked-data/commit/859f7bc7e9b00ba22c7c8b3ae23c2d2462822b36

Part of the data is added with this closing commit

**Comment by alistair3149** [comment]
Closing as completed
