### ISSUE TITLE
Include game data size number for vehicle

### ISSUE THREAD

**Issue by alistair3149** [StarCitizenWiki/API#59]
Would it be possible to include the [game data vehicle size](https://github.com/StarCitizenWiki/scunpacked-data/blob/859f7bc7e9b00ba22c7c8b3ae23c2d2462822b36/v2/ships/aegs_avenger_stalker.json#L7) in the API?

Ship matrix size is sometimes inconsistent with what is in the game data ([see here](https://starcitizen.tools/Ships#Definitions) for example)

**Comment by octfx** [comment]
Should now be accessible under the `size_class` key.
