### ISSUE TITLE
Talon should not have the missile hardpoint from Talon Shrike

### ISSUE THREAD

**Issue by alistair3149** [StarCitizenWiki/API#72]
It seems that Talon has the missile hardpoints and racks that are exclusive to Talon Shrike. Similar things have happened with Constellation and 300 series before too, maybe there's other way to differentiate whether a hardpoint exist on a variant?

**Comment by octfx** [comment]
Yeah, I guess I'll revert 55bec86ce619231174b3e493e5a1f38a073d0339
And only import
- Gravity Generator
- Life support

From the `Vehicle.Parts` array.

**Comment by alistair3149** [comment]
I think for Talon specifically it seems that the hardpoint is "activated" with the definitions inside the `modifications` key. https://github.com/StarCitizenWiki/scunpacked-data/blob/3cfde6041ea161d09b721ef42e278598468c0b2a/v2/ships/espr_talon-raw.json#L3547

Maybe it can be utilized somehow?
