### ISSUE TITLE
Determine whether an item can be stored in inventory

### ISSUE THREAD

**Issue by alistair3149** [StarCitizenWiki/API#78]
Some food items can not be stored in inventory (e.g. hotdog, ice cream, etc.)
It would be nice to know whether an item can be stored in inventory.

One possible solution is to detect whether there is a `Store` action under `SEntityInteractableParams`. Maybe there are better ways but I am unsure.

**Comment by octfx** [comment]
Done via 1fb07285bb409840f1ae1db4d2608a5cefe23794

All interactions of an item are now found on the `interactions` key
