### ISSUE TITLE
Missing shop data for mining modules

### ISSUE THREAD

**Issue by alistair3149** [StarCitizenWiki/API#79]
Brandt Module is missing the shop data. ([Wiki API](https://api.star-citizen.wiki/api/v2/items/18a62ae8-e1aa-453f-8631-df928a71abda?include=shops) vs [UIF](https://finder.cstone.space/ShipMiningMods1/18a62ae8-e1aa-453f-8631-df928a71abda))

**Comment by octfx** [comment]
Fixed in d00de761d8fa00f5d8673618c987109e4a7aa3c8
