### ISSUE TITLE
Add F8C Lightning

### ISSUE THREAD

**Issue by alistair3149** [StarCitizenWiki/API#83]
Now that F8C is flight ready, its in game data and pledge store info should be added to the API.

**Comment by octfx** [comment]
Imported the data just now!
| Classname | UUID |
| - | - |
|ANVL_Lightning_F8C| 663b6047-5b06-489c-a906-bc91fb7d6e63|
|ANVL_Lightning_F8C_Exec| b67123fd-72b3-43e7-bfb3-069d59ba6190|
|ANVL_Lightning_F8C_Plat | 71ac02d7-7345-4409-9d60-25def73279be|

Pledge prices still missing, as the ship upgrade tool does not list the F8C
