### ISSUE TITLE
F8C not returning FOCI as array

### ISSUE THREAD

**Issue by kingultron99** [StarCitizenWiki/API#85]
I've noticed that the F8C does not return its `foci` as an array like most other ships.

requesting a 100i gives me the following response:
```js
[
  { en_EN: 'Starter', de_DE: 'Einsteiger' },
  { en_EN: 'Touring', de_DE: 'Reisen' }
]
```
an 890j will give me:
```js
[ 
  { en_EN: 'Luxury Touring', de_DE: 'Luxus-Reisen' } 
]
```
but an F8C will give me:
```js
{ en_EN: 'Combat' }
```

appears to be the only ship that returns its foci this way from what I have found so far.

**Comment by octfx** [comment]
Thanks for the report!
Fix deployed, change should be live in the following hours
