### ISSUE TITLE
Keywords like 85x pulls non related article.

### ISSUE THREAD

**Issue by austinkschmitz** [StarCitizenWiki/API#89]
`curl -X 'POST' \
  'https://api.star-citizen.wiki/api/v2/galactapedia/search' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "query": "85x"
}'`

returns
The 85x article and Ellis Belt Alpha. 

`{
      "id": "0Gz5jL9vgP",
      "title": "85x",
      "slug": "origin-85x",
      "thumbnail": "https://cig-galactapedia-prod.s3.amazonaws.com/upload/973b4072-d906-4bd6-bb91-7a425f2c6450",
      "type": "SpacecraftShip",
      "rsi_url": "https://robertsspaceindustries.com/galactapedia/article/0Gz5jL9vgP-origin-85x",
      "api_url": "https://api.star-citizen.wiki/api/v2/galactapedia/0Gz5jL9vgP",
      "created_at": "2021-02-08T00:46:03.000000Z"
    },
    {
      "id": "02k585XkQe",
      "title": "Ellis Belt Alpha",
      "slug": "ellis-belt-alpha",
      "thumbnail": "https://cig-galactapedia-prod.s3.amazonaws.com/upload/bbd1aafa-d286-484b-ab90-63c1ec6a7ed1",
      "type": "PlanetMoonSpaceStationPlatform",
      "rsi_url": "https://robertsspaceindustries.com/galactapedia/article/02k585XkQe-ellis-belt-alpha",
      "api_url": "https://api.star-citizen.wiki/api/v2/galactapedia/02k585XkQe",
      "created_at": "2022-04-27T00:01:35.000000Z"
    }`

Per: https://robertsspaceindustries.com/galactapedia/search?query=85x
Only shows 1 article.

**Comment by octfx** [comment]
That’s due do the search endpoint also checking the id.
Which in this case contains 85x.

But that’s not really useful here, I’ll update the endpoint in the next release

**Comment by austinkschmitz** [comment]
Ah, that is good to know. Ty!
