### ISSUE TITLE
Making TractorBeam, SalvageModifier stats available

### ISSUE THREAD

**Issue by alistair3149** [StarCitizenWiki/API#93]
Currently, the [JSON files](https://github.com/StarCitizenWiki/scunpacked-data/blob/128dda7c5fc0f6b19650228858d6da222bcc39d7/v2/items/grin_tractorbeam_s2-raw.json) from SCUnpacked does not contain any stats on the tractor beams.

For tractor beams. stats below would be helpful to the community:
- Force
- Range
- Full strength distance
- Max angle
- Max volume

On a side note. SalvageModifier can be different modules such as Tractor Module or Scraper Module. Those stats are not available on the API yet as well.

**Comment by octfx** [comment]
Are these the correct values for `GRIN_TractorBeam_S2`?
```XML
<SWeaponActionFireTractorBeamParams
name="TractorBeam"
minForce="1500"
maxForce="1350000"
additionalForceDuringZeroGHandholding="0"
minDistance="0.5"
maxDistance="150"
fullStrengthDistance="75"
maxAngle="60"
maxVolume="10000">

```

**Comment by alistair3149** [comment]
Looks like it compared to game strings

**Comment by alistair3149** [comment]
Thanks for adding the tractor beam stats! It seems that some of the stats should also transfer to towing beam as well.
Here's the UUID for the towing beam on the SRV: `fd3625ad-6dce-4a48-ac86-3c7f8f09e11f`

**Comment by octfx** [comment]
Added in 2fcc68cbffe15153c2a00dc52327d5f0ecca9571 :)
