### ISSUE TITLE
Consider adding more detailed stats for missiles

### ISSUE THREAD

**Issue by alistair3149** [StarCitizenWiki/API#94]
* Speed
* Lock distance
* Lock angle
* Tracking signal
* Explosion radius
* Cluster count (e.g. Rattler II)
* Arm time

**Comment by octfx** [comment]
Added in 2e15578dfbb0a35a826d2a5f01ab1154a65f6bd5

For the cluster count I've used the number of ports present on a missile, which is `7` for the Rattler II and `1` for missiles that do not cluster
