### ISSUE TITLE
Manufacturers endpoint, has mis-named brands and duplicates

### ISSUE THREAD

**Issue by kingultron99** [StarCitizenWiki/API#97]
Various brands such as Firestorm Kinetics (FSKI) and MaxOx (MXOX) have been named "Aegis Dynamics".

Additionally, there are a _lot_ of duplicate entries for brands are present throughout the response, these duplicate brands also do not have any brand code attached to them, including:
- "Crusader Industries" appearing 45 times
- "Drake Interplanetary" appearing 62 times
- "Ace Astrogen" appearing 58 times
- etc

![image](https://github.com/StarCitizenWiki/API/assets/43083934/b1c6b1a9-65a0-46e7-9633-c88738f4a3cb)
(credit to Strangelove (Ex-Juval))

![image](https://github.com/StarCitizenWiki/API/assets/43083934/0b838813-eff7-472e-94f3-8e7fcb16f6eb)

**Comment by octfx** [comment]
That’s on CIG :/
The index just lists all manufacturers found for all items

You’ll get all items and vehicles of a given manufacturer when querying for it’s name e.g. manufacturers/Aegis%20Dynamics though
