### ISSUE TITLE
P8-AR returning 404 from items endpoint

### ISSUE THREAD

**Issue by kingultron99** [StarCitizenWiki/API#98]
Requesting the Behring P8-AR Rifle from `/api/v2/items/P8-AR Rifle` or by its UUID `957822ba-821d-47aa-a2f8-22d5e1321de` returns a 404 status code.

the item is listed under `/api/v2/items` and its manufacturer `/api/v2/manufacturers/behr`

**Comment by octfx** [comment]
Good catch! This was missing documentation.  
The P8-AR in question was removed in 3.14+, hence it lists its version as 3.14...

The `/items` endpoint per default only outputs items for the current game version. As 3.14 is not 3.22 the endpoints returns a 404.

I'll scope all items to the current game version for now, until I expand all endpoints to allow including items from previous versions.
